enum NameSpace {
  MOVIES = 'MOVIES',
  SELECTED_GENRE = 'SELECTED_GENRE',
  USER = 'USER',
  COMMENTS = 'COMMENTS',
  POST_COMMENT = 'POST_COMMENT',
  FAVORITES = 'FAVORITES',
}

export default NameSpace;
